### ISSUE TITLE
Installing shared LED maps makes Lulu unresponsive

### ISSUE THREAD

**Issue by jtgamble** [boardsource/pegBoards#15]
Downloading and saving an LED map from the shared maps results in the Lulu LEDs & OLEDs all going dark and key presses becoming unresponsive. To resolve you must set a custom LED map and save it to the board.

Repro steps:
1. From the LED mapping menu, click "Download more LED maps"
2. Select any LED map from the available maps and click "More Info"
3. Click Add to Board
4. Click Save Map

Result:
All LEDs on the Lulu turn off, both OLED screens go blank, and all keys stop responding.

Expected result:
The downloaded LED map is successfully applied.

**Comment by supersweet-dev** [comment]
Following repro steps got me to an unresponsive state that could only be fixed by wiping my lulu and redoing the initial set up. Attempts to write a custom map with debug on before reset show the write process wouldn't even start. Happens on Windows 11 and MacOS.

**Comment by daysgobye** [comment]
thank you for the bug report I will get right on it

**Comment by daysgobye** [comment]
fixed in newest build
