### ISSUE TITLE
Peg hangs once selecting 'Custom Codes' on Keymap tab

### ISSUE THREAD

**Issue by peott-fr** [boardsource/pegBoards#17]
Steps: (windows 10 machine)
* Open Peg (Lulu58 plugged-in)
* Go to Keymap tab
* Select 'Custom Codes'

Peg then hangs. I need to restart it.

**Comment by nichtayl** [comment]
Same here, seems to just be "Custom Codes" so far.

**Comment by supersweet-dev** [comment]
Pretty sure this only happens if you click on the tab without having added any custom codes first. Should be an easy fix, for whoever tackles it, but for now I'd just try to avoid that condition.

**Comment by jtgamble** [comment]
I found the same as @supersweet-dev. If you have created and saved a custom code then the hang doesn't occur.

**Comment by peott-fr** [comment]
My Peg has no Custom Codes at all. This problem started from the very first moment I installed and opened Peg.

**Comment by daysgobye** [comment]
you are all correct I need to catch that when you have no custom codes but you go to the tab it will hang I will get on it. Thank you for your input.

**Comment by daysgobye** [comment]
fixed in newest build
