### ISSUE TITLE
Cannot use `TapDance` in Peg

### ISSUE THREAD

**Issue by FirelightFlagboy** [boardsource/pegBoards#21]
I'm trying to configure `TapDance` on my Lulu keyboard.
I've created the following custom keycode for that:

```json
{
  "code": "KC.TD(KC.LCTRL, KC.MO(1))",
  "display": "TD-LCTR-MO(1)",
  "keybinding": "",
  "canHaveSub": false,
  "canHaveSubNumber": false,
  "subNumber": 0,
  "Description": "Tap once for LCTRL, Tap twice for momentary enable layer 1"
}
```

But when I hit `save map` on Peg, the board seems to be stuck at `main.py output:`.

I've manage to fix manually my problem by adding the module `TapDance` to the keyboard enabled modules.

```diff
 from kmk.modules.split import Split, SplitSide, SplitType
+from kmk.modules.tapdance import TapDance
 keyboard = KMKKeyboard()
 modtap = ModTap()
+tapdance = TapDance()
 layers_ext = Layers()
 keyboard.modules.append(layers_ext)
 keyboard.modules.append(modtap)
+keyboard.modules.append(tapdance)
 # oled
```

This fix work but these change are overwritten every time I `save map` on peg

**Comment by FirelightFlagboy** [comment]
One way to correct this issue is to add the following code in `main.py` bellow the lines with `keyboard.modules.append(...)`

```python
# codeblock
from kmk.modules.tapdance import TapDance
tapdance = TapDance()
keyboard.modules.append(tapdance)
# codeblock
```

**Comment by daysgobye** [comment]
yes, the above response is the entended fix. This is why we made code blocks so that you can have python stick around
