### ISSUE TITLE
RGB T only works with the left half.

### ISSUE THREAD

**Issue by cxj05h** [boardsource/pegBoards#26]
![image](https://user-images.githubusercontent.com/22186535/192107842-333d4933-2079-44c5-9c91-71aaf4c8e654.png)

This will turn off RGB for the left half but lighting remains on the right side.

**Comment by cxj05h** [comment]
just read about this in the documentation... : )

**Comment by daysgobye** [comment]
ummm strange what keyboard are you using?

**Comment by cxj05h** [comment]
> ummm strange what keyboard are you using?

Lulu. 
Checking again now to make sure and it's still only turned off LEDs on the left half even when the key is mirrored on both halves on a layer.

**Comment by cdparks** [comment]
I'm having the same problem with Lulu - tried to map RGB-T to left and right encoder-press, and they only toggle the left-hand-side. Is there a way to disable the leds completely in PEG?

**Comment by cxj05h** [comment]
This has now been resolved for me...just accidentally hit the key and both halves turned off...
