### ISSUE TITLE
super laggy on windows 11, some styling issue

### ISSUE THREAD

**Issue by scorp200** [boardsource/pegBoards#3]
- when the app is open, trying to drag or resize the window freezes the app and windows explorer.
- whole app very laggy to interact with
- styling issue
![image](https://user-images.githubusercontent.com/9427639/171927445-9cc992b8-7da6-437b-b26a-7d0989da5e9d.png)

**Comment by LukeDRussell** [comment]
The window completely freezes for me, on Win11. I can't bring the window to the foreground even. Doesn't respond to graceful 'Close', I have to use Task Manager to kill the Peg processes (6 or 7).

**Comment by daysgobye** [comment]
I pushed a new build up if you can download it and see if its fixed :) thank you for your bug report we really appreciate it.

**Comment by scorp200** [comment]
> I pushed a new build up if you can download it and see if its fixed :) thank you for your bug report we really appreciate it.

seems like that fixed the issue, i can actually move and interact with the window,
