### ISSUE TITLE
RGB_TOG doesn't work on splits

### ISSUE THREAD

**Issue by kdb424** [boardsource/pegBoards#6]
Data isn't sent to the other half it would seem when trying to turn off RGB. This is technically a module issue, though I'm cross reporting it here as it's a PEG module mostly.

**Comment by daysgobye** [comment]
https://peg.software/docs/Peg_Client/#rgb_tog-does-not-toggle-both-sides-of-split-keyboard

**Comment by daysgobye** [comment]
does this fix it for you?
